#ifndef CHUCKRUM_CHAINPARAMSSEEDS_H
#define CHUCKRUM_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the chuckrum network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside an IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
<<<<<<< HEAD
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x23,0xde,0x42,0x07}, 7444}
};

static SeedSpec6 pnSeed6_test[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x23,0xde,0x42,0x07}, 17444}
=======
};

static SeedSpec6 pnSeed6_test[] = {

>>>>>>> f76d7718b1c961f2f6d1f94e4832ed77448f3c90
};
#endif // CHUCKRUM_CHAINPARAMSSEEDS_H
